### ISSUE TITLE
The size of the input variable in callback.c differs from the size required by nnb.

### ISSUE THREAD

**Issue by MizunagiKB** [sony/nnabla-c-runtime#83]
This is a confirmation on the following code.
> https://github.com/sony/nnabla-c-runtime/blob/master/examples/callback/callback.c

At the beginning of this code, there is an explanation of _affine_nnb_, which says that it takes (1, 4, 6) values in FLOAT32, but the input passed in the code is 24 bytes.

In reality, it is FLOAT32, so it reads as 1 * 4 * 6 * sizeof(float), which means that 96 bytes must be passed.

Or is it that you are working with INT8 instead of FLOAT32?

**Comment by TomonobuTsujikawa** [comment]
Thank you for creating the issue.
We have checked this issue carefully, and your concern is right.
Sorry for late my answer.

Furthermore, thank you for creating the PR to overcome this issue.
We'll review your PR as soon as possible.

**Comment by MizunagiKB** [comment]
Thanks for the merge.
I discovered this pull request while integrating nnabla_c_runtime into GodotEngine 4.1.
* https://github.com/MizunagiKB/gd_nnabla_c_runtime

NNabla, nnabla_c_runtime and NNC are what got me exposed to machine learning, so I am glad you merged them.
